name: nittfest
description: App for Nittfest.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  get_storage:
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0
  flutter_local_notifications: ^5.0.0+4
  webviewx: ^0.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
