name: nittfest
description: App for Nittfest.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  expandable: ^5.0.1
  get_storage:
  curved_navigation_bar: ^1.0.3
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.4.0
  webviewx: ^0.2.1
  google_fonts: ^2.3.1
  youtube_player_flutter: ^8.0.0
  url_launcher:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
