var teamContent = {
  'OC':
      'The NITTFEST organising committee is the bridge between all the other teams in the fest. Our work encompasses multiple activities from admin relations, tills inventory and T-Shirts.\nFrom this team you’ll be able to takeaway how to understand and communicate with people. If you’re one to be responsible and know to have a lot of fun and want to make new friends then NOC has a place for you.',
  'EVENTS':
      'If you\'re the type to come up with the wildest ideas and live to see them realised, you\'d be a great fit for the NITTFEST Events Team. Our team prides in organising multiple offline and online events to keep the fest buzz going. Our main goal is to make the battle of departments a fair and enjoyable experience.\nApart from having the creative space to ideate, learning event management, and managing people, this team is a place to have fun, think out of the box and grow. NET looks for people with great creativity yet practicality, sheer dedication and hardwork.',
  'AMBIENCE':
      'Team Ambience is in charge of creating a joyous feel for Nittfest by combining art and technology to create an elegant atmosphere.\nWith our stunning displays and unique characters that add charm to the fest, we light up the campus with our gorgeous lamps and recreate the place to enjoy.\nWe Ideate, Collaborate, Design, model, and Install on site in and around campus during the fest.\n\nWe add an experienced palette to all the happening spaces within the campus through setting the ambience of the overall mood to Nittfest.\n\nIf you are one with an artistic flair and a creative mind then Ambience is the place for you.\n',
  'PR&C':
      'The battle between the departments has been revived. And would it not be a sacrilege to not pen down the clash for the history books?\n\nTeam PRnC is looking for champion writers and talkers who can smooth talk their way into people’s hearts.\n\nWe need fresh MoCs who can sway the stage with their charm. And need we mention exciting opportunity to interview guests?\n\nAnd most importantly we need competent managers who can guide their fellow juniors.\n\nIf you believe you’ve got the energy and enthusiasm to be the public face of the fest, put your inner introvert aside and apply now!',
  'MARKETING':
      'NITTFest Marketing Team lays the groundwork for NITTFest, seeking to raise the bar with each edition.\n We are responsible for increasing overall brand awareness, while also driving potential and recurring companies towards NITTFest. With coverts of corporate giants like Puma, The Princeton Review, Nestle, NMT retains them, and helps NITTFest attain the monetary funds required for a successful fest.\nThe NITTFest Marketing Team gives you the chance to show off your ingenuity and creativity while making vital contacts with the business sector, where you may polish your talents and find your niche. If you enjoy interacting with businesses and cooperating with them on a regular basis, the NITTFest Marketing Team is the place for you.\n',
  'DESIGN':
      'You’ve seen the logo that shines above all. You\'ve seen the the colors that provide the backdrop for the glory.The Design team is at the helm of all that and much more. We bring out the fest in its artistic grandeur and put it out for the world to see.\nVideos, posters,illustrations, we’ve got it all.So if you’ve got ideas to bring out the life of the fest, or if you just have a taste for digital renderings, you\'ll fit right in.\nAll those with an artistic flair and a imaginative mind,\nhead on over and fill out our induction form!',
};
