name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  flutter_version: "2.8.x"

jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - if: github.event_name == 'pull_request'
        run: flutter format --dry-run . --set-exit-if-changed
      - if: github.event_name == 'pull_request'
        run:  flutter analyze 
      - if: github.event_name == 'push'
        run: flutter build apk
      - if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          